---
- name: "Fruits App Demo with Gloo Edge Community"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ####
    ## KinD cluster setup
    ####
    cluster_name: fruits-app-demo
    ####
    ## Gloo Edge Configuration
    ####
    # Gloo Edge Setup
    deploy_gloo_edge: true

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
