---
- name: "Fruits App Demo with Istio"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ####
    ## KinD cluster setup
    ####
    cluster_name: fruits-app-demo
    # valid values are ipv4, ipv6, dual
    kind_ip_family: ipv4
    # Create Cluster
    kind_create: false
    ####
    ## Istio Configurations
    ####
    deploy_istio: true
    ## Istio Ingress Gateway
    deploy_istio_gateway: true
    istio_versions:
      - "1.10.2"

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
