---
- name: "KinD Demo Cluster 1"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    cluster_name: cluster-1
    kind_create: true
    # Add your neded configuration here
    # https://kameshsampath.github.io/kubernetes_spices
  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
